### ISSUE TITLE
Provide a way to initialize an empty Docassemble repo locally, so you do not need to start from the Playground

### ISSUE THREAD

**Issue by nonprofittechy** [jhpyle/docassemblecli#7]
Editing locally is a great workflow, but currently you cannot initialize a Docassemble repo without starting in the playground. That's a clunky task that among other things, requires the GitHub integration to be created and turned on in the playground.

something like `create-react-app` would be great.

**Comment by jhpyle** [comment]
I agree with the feature request but I would note that GitHub integration does not need to be turned on in order to create a local repository. You can download a ZIP file of a package from the Playground Packages page, unzip it, and run `git init` inside the directory.
